### PR TITLE
DVX-8206 Fix Nginx configuration in ES clusters

### PR DESCRIPTION
**Pull request by ifosch**
This fixes the nginx configuration in such a way that EBT will not try to rewrite it.

Refs [DVX-8206](https://mydevex.atlassian.net/browse/DVX-8206)

### CODE REVIEW

**Comment by ifosch** [comment]
For reference: This fix was introduced to prevent Nginx from replying 502 on index creation requests, because of the size of queries. This morning with @nicolas-fricke we found this was still happening and this is the correct address as of [EB documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/java-se-nginx.html).

**Comment by towanda** [comment]
+1

**Comment by ifosch** [comment]
So far I have tested this in test, and I will use this to build up the new Develop cluster tonight.

**Comment by nicolas-fricke** [comment]
31

**Pull request merged**
